build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    sensiolabs_security_checker: true
